<Project Sdk="Microsoft.NET.Sdk.Worker">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>dotnet-SendEmailService.Worker-0ee43a21-a407-419e-83a4-0dd45df08b40</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Hosting" Version="8.0.1" />
    <PackageReference Include="Microsoft.Extensions.Hosting.WindowsServices" Version="8.0.1" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\SendEmailService.Core\SendEmailService.Core.csproj" />
    <ProjectReference Include="..\SendEmailService.Infrastructure\SendEmailService.Infrastructure.csproj" />
  </ItemGroup>
</Project>
